#set the name, addr and environment type for the server
name: "app:blueprint"
addr: ":4000"
env: "dev"

#set the amount of time to run the server.HeartBeats function
heartbeat: 5m

#set up the folders
folders:
  assets: ./assets
  models: ./app
  views: ./views

#set up the template folder and settings
templates:
  dir: ./templates
  ext: .tmpl

#use the generic db config parameters
db:
  name: apps
  type: "mysql"
  addr: "adminSiVKWXi:pPVgKKk-WzFS@tcp(localhost:3306)/godo"
